Garcia, Eoin Gamliel Rye Q.

In [10]:
import numpy as np

**NORMALIZATION PROBLEM**

In [13]:
#create a random 5x5 ndarray and store it to the variable X.
X = np.random.random((5,5))
X

array([[0.80001772, 0.05401361, 0.9699225 , 0.20526426, 0.27334176],
       [0.01405157, 0.05670422, 0.12337527, 0.88715566, 0.64047495],
       [0.65687089, 0.53925825, 0.59973411, 0.47996183, 0.85553678],
       [0.89028017, 0.19001815, 0.80504511, 0.61455126, 0.48466836],
       [0.04330203, 0.11748968, 0.12632074, 0.5253832 , 0.80124481]])

In [16]:
#Normalizing X

#Obtain the element-wise mean
X_mean = X.mean()

#Obtain the element-wise standard deviation
X_std = X.std()

#Use the given formula to obtain normalization
X_normalized = (X - X_mean) / X_std
X_normalized

array([[ 1.04867895, -1.32300288,  1.58883693, -0.84214975, -0.62571906],
       [-1.45004943, -1.31444893, -1.10248964,  1.32570619,  0.54146366],
       [ 0.5935893 ,  0.21967749,  0.41194118,  0.03116346,  1.22518405],
       [ 1.33563958, -0.89061989,  1.06466192,  0.45904756,  0.04612638],
       [-1.35705693, -1.12120098, -1.09312545,  0.1755662 ,  1.05258007]])

In [21]:
#Save the normalized ndarray as X_normalized.npy
np.save ('X_normalized.npy', X_normalized)

In [24]:
#Output arrays
print ("Array X: \n" , X)
print ("\nNormalized Array X: \n" , X_normalized)

Array X: 
 [[0.80001772 0.05401361 0.9699225  0.20526426 0.27334176]
 [0.01405157 0.05670422 0.12337527 0.88715566 0.64047495]
 [0.65687089 0.53925825 0.59973411 0.47996183 0.85553678]
 [0.89028017 0.19001815 0.80504511 0.61455126 0.48466836]
 [0.04330203 0.11748968 0.12632074 0.5253832  0.80124481]]

Normalized Array X: 
 [[ 1.04867895 -1.32300288  1.58883693 -0.84214975 -0.62571906]
 [-1.45004943 -1.31444893 -1.10248964  1.32570619  0.54146366]
 [ 0.5935893   0.21967749  0.41194118  0.03116346  1.22518405]
 [ 1.33563958 -0.89061989  1.06466192  0.45904756  0.04612638]
 [-1.35705693 -1.12120098 -1.09312545  0.1755662   1.05258007]]


**DIVISIBLE BY 3 PROBLEM**

In [25]:
#Make a 10x10 ndarray that contains the squares of the first 100 positive integers
A = np.arange (1,101)**2
A = A.reshape (10,10)
A

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [ ]:
#Determine the elements that are divisible by 3
div_by_3 = A[A % 3 == 0]
div_by_3

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [ ]:
#Save the ndarray as div_by_3.npy
np.save ('div_by_3.npy', div_by_3)

In [ ]:
#Output the ndarray
print ("Array A: \n", A)
print ("\nElements divisible by 3: \n", div_by_3)

Array A: 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3: 
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
